spring:
  config:
    activate:
      on-profile: dev

cloud:
  aws:
    s3:
      bucket: "bucket-dev"
    credentials:
      accessKey: "accessKey"
      secretKey: "secretKey"
    region: us-east-2
    stack:
      auto: false